services:
  mongo:
    image: mongo:8.0 
    container_name: covoiturage-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: covoiturage
    volumes:
      - mongo_data:/data/db

  app:
    image: covoiturage-aap    # l'image construit avec docker build
    container_name: covoiturage-app
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8082:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/covoiturage

volumes:
  mongo_data:
